"""
Seed data for the Internship & Placement Engine.

50 internships + 50 placement jobs across:
  Bosch, Google, Microsoft, Amazon, Qualcomm, Intel,
  Texas Instruments, ABB, Siemens, Mercedes, L&T,
  Infosys, TCS, Accenture

Each entry:
  company      : must match company name in seed_companies.py
  title        : posting title
  type         : TECHNICAL / RESEARCH / MANAGEMENT / DESIGN / DATA
  mode         : REMOTE / HYBRID / ONSITE
  stipend_inr  : monthly stipend (internships only)
  duration     : internship duration string
  pkg_min/max  : package in LPA (placements only)
  location     : city
  openings     : number of seats
  min_score    : minimum readiness score (0-100)
  min_cgpa     : minimum CGPA
  branches     : comma-separated branch codes (None = all branches)
  description  : short description
  eligibility  : human-readable eligibility text
"""
from datetime import date

INTERNSHIP_SEED = [
    # ── Google ────────────────────────────────────────────────────────────────
    {
        "company": "Google India",
        "title": "Software Engineering Intern – AI/ML",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 80000,
        "duration": "3 months",
        "location": "Bangalore",
        "openings": 10,
        "min_score": 60.0,
        "min_cgpa": 8.0,
        "branches": "AIML",
        "description": "Work on cutting-edge ML models and large-scale data pipelines at Google's India AI lab.",
        "eligibility": "B.Tech 3rd/4th year, AIML branch, CGPA >= 8.0, Readiness >= 60",
        "apply_link": "https://careers.google.com/india",
        "app_start": date(2025, 9, 1),
        "app_end": date(2025, 9, 30),
    },
    {
        "company": "Google India",
        "title": "Data Science Intern",
        "type": "DATA",
        "mode": "REMOTE",
        "stipend": 70000,
        "duration": "2 months",
        "location": "Remote",
        "openings": 5,
        "min_score": 50.0,
        "min_cgpa": 7.5,
        "branches": "AIML",
        "description": "Analyze large datasets and build predictive models for Google's product teams.",
        "eligibility": "B.Tech 2nd/3rd year, AIML, CGPA >= 7.5, Readiness >= 50",
        "apply_link": "https://careers.google.com/india",
        "app_start": date(2025, 10, 1),
        "app_end": date(2025, 10, 31),
    },
    {
        "company": "Google India",
        "title": "Research Intern – Deep Learning",
        "type": "RESEARCH",
        "mode": "ONSITE",
        "stipend": 90000,
        "duration": "6 months",
        "location": "Hyderabad",
        "openings": 3,
        "min_score": 70.0,
        "min_cgpa": 8.5,
        "branches": "AIML",
        "description": "Conduct research on deep learning architectures in collaboration with Google Brain.",
        "eligibility": "Final year B.Tech, AIML, CGPA >= 8.5, Readiness >= 70",
        "apply_link": "https://careers.google.com/india",
        "app_start": date(2025, 8, 1),
        "app_end": date(2025, 8, 20),
    },
    # ── Microsoft ─────────────────────────────────────────────────────────────
    {
        "company": "Microsoft",
        "title": "Azure Cloud Engineering Intern",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 75000,
        "duration": "3 months",
        "location": "Hyderabad",
        "openings": 8,
        "min_score": 55.0,
        "min_cgpa": 7.5,
        "branches": "AIML",
        "description": "Build cloud-native solutions on Microsoft Azure infrastructure.",
        "eligibility": "3rd/4th year B.Tech, AIML, CGPA >= 7.5, Readiness >= 55",
        "apply_link": "https://careers.microsoft.com/india",
        "app_start": date(2025, 9, 5),
        "app_end": date(2025, 10, 5),
    },
    {
        "company": "Microsoft",
        "title": "AI Research Intern",
        "type": "RESEARCH",
        "mode": "HYBRID",
        "stipend": 85000,
        "duration": "6 months",
        "location": "Bangalore",
        "openings": 4,
        "min_score": 65.0,
        "min_cgpa": 8.0,
        "branches": "AIML",
        "description": "Work on next-generation AI systems for Microsoft Research India.",
        "eligibility": "Final year B.Tech, AIML, CGPA >= 8.0, Readiness >= 65",
        "apply_link": "https://careers.microsoft.com/india",
        "app_start": date(2025, 11, 1),
        "app_end": date(2025, 11, 30),
    },
    # ── Amazon ────────────────────────────────────────────────────────────────
    {
        "company": "Amazon Web Services India",
        "title": "MLOps Intern",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 70000,
        "duration": "3 months",
        "location": "Hyderabad",
        "openings": 6,
        "min_score": 55.0,
        "min_cgpa": 7.5,
        "branches": "AIML",
        "description": "Build and automate ML model deployment pipelines on AWS SageMaker.",
        "eligibility": "3rd/4th year B.Tech, AIML, CGPA >= 7.5",
        "apply_link": "https://amazon.jobs/india",
        "app_start": date(2025, 9, 10),
        "app_end": date(2025, 10, 10),
    },
    {
        "company": "Amazon Web Services India",
        "title": "Cloud Solutions Architect Intern",
        "type": "TECHNICAL",
        "mode": "REMOTE",
        "stipend": 65000,
        "duration": "2 months",
        "location": "Remote",
        "openings": 5,
        "min_score": 45.0,
        "min_cgpa": 7.0,
        "branches": "AIML",
        "description": "Design and prototype cloud architecture solutions for enterprise customers.",
        "eligibility": "2nd/3rd year B.Tech, any branch",
        "apply_link": "https://amazon.jobs/india",
        "app_start": date(2025, 10, 15),
        "app_end": date(2025, 11, 15),
    },
    # ── Qualcomm ──────────────────────────────────────────────────────────────
    {
        "company": "Qualcomm India",
        "title": "VLSI Design Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 60000,
        "duration": "6 months",
        "location": "Bangalore",
        "openings": 5,
        "min_score": 55.0,
        "min_cgpa": 7.5,
        "branches": "ECE",
        "description": "Work on next-gen 5G chip design verification at Qualcomm's India R&D center.",
        "eligibility": "3rd/4th year B.Tech, ECE, CGPA >= 7.5",
        "apply_link": "https://www.qualcomm.com/careers",
        "app_start": date(2025, 8, 1),
        "app_end": date(2025, 8, 31),
    },
    {
        "company": "Qualcomm India",
        "title": "Embedded Systems Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 55000,
        "duration": "3 months",
        "location": "Hyderabad",
        "openings": 4,
        "min_score": 50.0,
        "min_cgpa": 7.0,
        "branches": "ECE",
        "description": "Develop and test embedded firmware for Qualcomm's Snapdragon platform.",
        "eligibility": "3rd/4th year B.Tech, ECE, CGPA >= 7.0",
        "apply_link": "https://www.qualcomm.com/careers",
        "app_start": date(2025, 9, 1),
        "app_end": date(2025, 9, 30),
    },
    {
        "company": "Qualcomm India",
        "title": "RF Systems Research Intern",
        "type": "RESEARCH",
        "mode": "ONSITE",
        "stipend": 65000,
        "duration": "6 months",
        "location": "Bangalore",
        "openings": 2,
        "min_score": 60.0,
        "min_cgpa": 8.0,
        "branches": "ECE",
        "description": "Research advanced RF algorithms for millimeter-wave 5G communications.",
        "eligibility": "Final year B.Tech, ECE, CGPA >= 8.0",
        "apply_link": "https://www.qualcomm.com/careers",
        "app_start": date(2025, 10, 1),
        "app_end": date(2025, 10, 20),
    },
    # ── Intel ─────────────────────────────────────────────────────────────────
    {
        "company": "Intel India",
        "title": "FPGA Design Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 58000,
        "duration": "6 months",
        "location": "Bangalore",
        "openings": 4,
        "min_score": 50.0,
        "min_cgpa": 7.5,
        "branches": "ECE",
        "description": "Design and implement FPGA-based accelerators for AI inference workloads.",
        "eligibility": "3rd/4th year B.Tech, ECE, CGPA >= 7.5",
        "apply_link": "https://jobs.intel.com/india",
        "app_start": date(2025, 8, 15),
        "app_end": date(2025, 9, 15),
    },
    {
        "company": "Intel India",
        "title": "AI Hardware Intern",
        "type": "RESEARCH",
        "mode": "HYBRID",
        "stipend": 65000,
        "duration": "3 months",
        "location": "Hyderabad",
        "openings": 3,
        "min_score": 60.0,
        "min_cgpa": 8.0,
        "branches": "AIML,ECE",
        "description": "Co-optimize neural networks with Intel's hardware architecture team.",
        "eligibility": "Final year B.Tech, AIML or ECE, CGPA >= 8.0",
        "apply_link": "https://jobs.intel.com/india",
        "app_start": date(2025, 11, 1),
        "app_end": date(2025, 11, 30),
    },
    # ── Texas Instruments ─────────────────────────────────────────────────────
    {
        "company": "Texas Instruments India",
        "title": "Analog Design Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 55000,
        "duration": "6 months",
        "location": "Bangalore",
        "openings": 5,
        "min_score": 50.0,
        "min_cgpa": 7.5,
        "branches": "ECE,EEE",
        "description": "Design and simulate analog circuits for power management ICs.",
        "eligibility": "3rd/4th year B.Tech, ECE or EEE, CGPA >= 7.5",
        "apply_link": "https://careers.ti.com",
        "app_start": date(2025, 7, 1),
        "app_end": date(2025, 8, 1),
    },
    {
        "company": "Texas Instruments India",
        "title": "DSP Algorithm Intern",
        "type": "RESEARCH",
        "mode": "ONSITE",
        "stipend": 60000,
        "duration": "3 months",
        "location": "Hyderabad",
        "openings": 3,
        "min_score": 55.0,
        "min_cgpa": 7.5,
        "branches": "ECE",
        "description": "Develop and optimize DSP algorithms for audio and communications applications.",
        "eligibility": "Final year B.Tech, ECE, CGPA >= 7.5",
        "apply_link": "https://careers.ti.com",
        "app_start": date(2025, 9, 15),
        "app_end": date(2025, 10, 15),
    },
    # ── ABB ───────────────────────────────────────────────────────────────────
    {
        "company": "ABB India",
        "title": "Power Systems Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 45000,
        "duration": "3 months",
        "location": "Bangalore",
        "openings": 6,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "EEE",
        "description": "Work on grid automation and protection systems at ABB's power division.",
        "eligibility": "3rd/4th year B.Tech, EEE, CGPA >= 7.0",
        "apply_link": "https://new.abb.com/careers/india",
        "app_start": date(2025, 8, 1),
        "app_end": date(2025, 9, 1),
    },
    {
        "company": "ABB India",
        "title": "Industrial Automation Intern",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 42000,
        "duration": "6 months",
        "location": "Nashik",
        "openings": 4,
        "min_score": 40.0,
        "min_cgpa": 6.5,
        "branches": "EEE,Mechanical",
        "description": "Design and commission PLC-based automation systems for manufacturing lines.",
        "eligibility": "3rd/4th year B.Tech, EEE or Mechanical, CGPA >= 6.5",
        "apply_link": "https://new.abb.com/careers/india",
        "app_start": date(2025, 10, 1),
        "app_end": date(2025, 11, 1),
    },
    # ── Siemens ───────────────────────────────────────────────────────────────
    {
        "company": "Siemens India",
        "title": "Drives & Motors Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 48000,
        "duration": "3 months",
        "location": "Pune",
        "openings": 5,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "EEE",
        "description": "Commissioning and testing of Siemens variable frequency drives and motors.",
        "eligibility": "3rd/4th year B.Tech, EEE, CGPA >= 7.0",
        "apply_link": "https://www.siemens.co.in/careers",
        "app_start": date(2025, 9, 1),
        "app_end": date(2025, 9, 30),
    },
    {
        "company": "Siemens India",
        "title": "Building Technologies Intern",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 44000,
        "duration": "2 months",
        "location": "Mumbai",
        "openings": 6,
        "min_score": 35.0,
        "min_cgpa": 6.5,
        "branches": "EEE,Mechanical",
        "description": "Work on HVAC automation and smart building systems integration.",
        "eligibility": "2nd/3rd year B.Tech, EEE or Mechanical, CGPA >= 6.5",
        "apply_link": "https://www.siemens.co.in/careers",
        "app_start": date(2025, 11, 1),
        "app_end": date(2025, 11, 30),
    },
    # ── Bosch ─────────────────────────────────────────────────────────────────
    {
        "company": "Bosch India",
        "title": "Embedded C Intern – Automotive",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 50000,
        "duration": "6 months",
        "location": "Bangalore",
        "openings": 8,
        "min_score": 50.0,
        "min_cgpa": 7.5,
        "branches": "ECE,EEE",
        "description": "Develop and test ECU firmware for automotive safety-critical systems.",
        "eligibility": "3rd/4th year B.Tech, ECE or EEE, CGPA >= 7.5",
        "apply_link": "https://www.bosch.in/careers",
        "app_start": date(2025, 8, 15),
        "app_end": date(2025, 9, 15),
    },
    {
        "company": "Bosch India",
        "title": "AI Vision Intern – ADAS",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 60000,
        "duration": "3 months",
        "location": "Coimbatore",
        "openings": 4,
        "min_score": 55.0,
        "min_cgpa": 7.5,
        "branches": "AIML,ECE",
        "description": "Develop computer vision algorithms for Advanced Driver Assistance Systems.",
        "eligibility": "3rd/4th year B.Tech, AIML or ECE, CGPA >= 7.5",
        "apply_link": "https://www.bosch.in/careers",
        "app_start": date(2025, 9, 1),
        "app_end": date(2025, 10, 1),
    },
    {
        "company": "Bosch India",
        "title": "Mechanical Design Intern",
        "type": "DESIGN",
        "mode": "ONSITE",
        "stipend": 42000,
        "duration": "6 months",
        "location": "Pune",
        "openings": 5,
        "min_score": 35.0,
        "min_cgpa": 7.0,
        "branches": "Mechanical",
        "description": "Design automotive components using CAD tools — SolidWorks and CATIA.",
        "eligibility": "3rd/4th year B.Tech, Mechanical, CGPA >= 7.0",
        "apply_link": "https://www.bosch.in/careers",
        "app_start": date(2025, 10, 1),
        "app_end": date(2025, 11, 1),
    },
    # ── Mercedes ──────────────────────────────────────────────────────────────
    {
        "company": "Mercedes-Benz India",
        "title": "Powertrain Engineering Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 55000,
        "duration": "6 months",
        "location": "Pune",
        "openings": 4,
        "min_score": 50.0,
        "min_cgpa": 7.5,
        "branches": "Mechanical",
        "description": "Analyze powertrain performance data and support engineering validations.",
        "eligibility": "3rd/4th year B.Tech, Mechanical, CGPA >= 7.5",
        "apply_link": "https://www.mercedes-benz.co.in/careers",
        "app_start": date(2025, 8, 1),
        "app_end": date(2025, 9, 1),
    },
    {
        "company": "Mercedes-Benz India",
        "title": "Body & Trim Design Intern",
        "type": "DESIGN",
        "mode": "HYBRID",
        "stipend": 50000,
        "duration": "3 months",
        "location": "Pune",
        "openings": 3,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "Mechanical",
        "description": "Support design engineers on vehicle body panel modelling and fit/finish analysis.",
        "eligibility": "3rd/4th year B.Tech, Mechanical, CGPA >= 7.0",
        "apply_link": "https://www.mercedes-benz.co.in/careers",
        "app_start": date(2025, 10, 15),
        "app_end": date(2025, 11, 15),
    },
    # ── L&T ───────────────────────────────────────────────────────────────────
    {
        "company": "L&T Technology Services",
        "title": "Electrical Systems Intern",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 40000,
        "duration": "3 months",
        "location": "Chennai",
        "openings": 10,
        "min_score": 30.0,
        "min_cgpa": 6.5,
        "branches": "EEE",
        "description": "Assist in design and commissioning of electrical systems for industrial projects.",
        "eligibility": "3rd/4th year B.Tech, EEE, CGPA >= 6.5",
        "apply_link": "https://www.larsentoubro.com/careers",
        "app_start": date(2025, 9, 1),
        "app_end": date(2025, 10, 1),
    },
    {
        "company": "L&T Technology Services",
        "title": "CAD/CAM Intern",
        "type": "DESIGN",
        "mode": "ONSITE",
        "stipend": 38000,
        "duration": "6 months",
        "location": "Vadodara",
        "openings": 8,
        "min_score": 30.0,
        "min_cgpa": 6.5,
        "branches": "Mechanical",
        "description": "Create and validate 3D models and 2D drawings using Pro-E/CATIA.",
        "eligibility": "3rd/4th year B.Tech, Mechanical, CGPA >= 6.5",
        "apply_link": "https://www.larsentoubro.com/careers",
        "app_start": date(2025, 10, 1),
        "app_end": date(2025, 11, 1),
    },
    {
        "company": "L&T Technology Services",
        "title": "IoT & Embedded Intern",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 42000,
        "duration": "3 months",
        "location": "Bangalore",
        "openings": 6,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "ECE,EEE",
        "description": "Build IoT device prototypes and test embedded firmware for industrial IoT solutions.",
        "eligibility": "3rd/4th year B.Tech, ECE or EEE, CGPA >= 7.0",
        "apply_link": "https://www.larsentoubro.com/careers",
        "app_start": date(2025, 11, 1),
        "app_end": date(2025, 12, 1),
    },
    # ── Infosys ───────────────────────────────────────────────────────────────
    {
        "company": "Infosys BPM",
        "title": "Data Analytics Intern",
        "type": "DATA",
        "mode": "HYBRID",
        "stipend": 35000,
        "duration": "2 months",
        "location": "Bangalore",
        "openings": 20,
        "min_score": 25.0,
        "min_cgpa": 6.0,
        "branches": None,
        "description": "Analyze business data and create dashboards using Power BI and Python.",
        "eligibility": "Any branch, 3rd/4th year B.Tech, CGPA >= 6.0",
        "apply_link": "https://www.infosys.com/careers/india",
        "app_start": date(2025, 8, 1),
        "app_end": date(2025, 9, 1),
    },
    {
        "company": "Infosys BPM",
        "title": "Software Development Intern",
        "type": "TECHNICAL",
        "mode": "REMOTE",
        "stipend": 30000,
        "duration": "3 months",
        "location": "Remote",
        "openings": 25,
        "min_score": 20.0,
        "min_cgpa": 6.0,
        "branches": None,
        "description": "Build full-stack web applications using React, Node.js, and AWS.",
        "eligibility": "Any branch, 2nd/3rd year B.Tech, CGPA >= 6.0",
        "apply_link": "https://www.infosys.com/careers/india",
        "app_start": date(2025, 10, 1),
        "app_end": date(2025, 11, 1),
    },
    # ── TCS ───────────────────────────────────────────────────────────────────
    {
        "company": "Tata Consultancy Services",
        "title": "Technology Analyst Intern",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 32000,
        "duration": "2 months",
        "location": "Mumbai",
        "openings": 30,
        "min_score": 20.0,
        "min_cgpa": 6.0,
        "branches": None,
        "description": "Work on enterprise digital transformation projects across domains.",
        "eligibility": "Any branch, 3rd/4th year B.Tech, CGPA >= 6.0",
        "apply_link": "https://www.tcs.com/careers",
        "app_start": date(2025, 9, 1),
        "app_end": date(2025, 10, 1),
    },
    {
        "company": "Tata Consultancy Services",
        "title": "IoT Solutions Intern",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 35000,
        "duration": "3 months",
        "location": "Hyderabad",
        "openings": 15,
        "min_score": 30.0,
        "min_cgpa": 6.5,
        "branches": "ECE,EEE,AIML",
        "description": "Develop IoT solutions using AWS IoT Core and edge computing platforms.",
        "eligibility": "3rd/4th year B.Tech, ECE, EEE or AIML, CGPA >= 6.5",
        "apply_link": "https://www.tcs.com/careers",
        "app_start": date(2025, 11, 1),
        "app_end": date(2025, 12, 1),
    },
    # ── Accenture ─────────────────────────────────────────────────────────────
    {
        "company": "Accenture India",
        "title": "AI Solutions Intern",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 40000,
        "duration": "3 months",
        "location": "Bangalore",
        "openings": 20,
        "min_score": 30.0,
        "min_cgpa": 6.5,
        "branches": "AIML",
        "description": "Implement AI-driven automation solutions for Accenture's enterprise clients.",
        "eligibility": "3rd/4th year B.Tech, AIML, CGPA >= 6.5",
        "apply_link": "https://www.accenture.com/in-en/careers",
        "app_start": date(2025, 9, 1),
        "app_end": date(2025, 10, 1),
    },
    {
        "company": "Accenture India",
        "title": "Consulting Intern",
        "type": "MANAGEMENT",
        "mode": "HYBRID",
        "stipend": 38000,
        "duration": "2 months",
        "location": "Pune",
        "openings": 15,
        "min_score": 25.0,
        "min_cgpa": 7.0,
        "branches": None,
        "description": "Assist consulting teams on digital strategy projects for manufacturing and energy clients.",
        "eligibility": "3rd/4th year B.Tech, any branch, CGPA >= 7.0",
        "apply_link": "https://www.accenture.com/in-en/careers",
        "app_start": date(2025, 10, 1),
        "app_end": date(2025, 11, 1),
    },
    {
        "company": "Accenture India",
        "title": "Embedded & IoT Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 42000,
        "duration": "3 months",
        "location": "Chennai",
        "openings": 10,
        "min_score": 35.0,
        "min_cgpa": 7.0,
        "branches": "ECE,EEE",
        "description": "Design IoT device firmware and integrate with cloud analytics platforms.",
        "eligibility": "3rd/4th year B.Tech, ECE or EEE, CGPA >= 7.0",
        "apply_link": "https://www.accenture.com/in-en/careers",
        "app_start": date(2025, 8, 15),
        "app_end": date(2025, 9, 15),
    },
    # Extra to reach 50
    {
        "company": "NVIDIA India",
        "title": "Deep Learning Frameworks Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 90000,
        "duration": "6 months",
        "location": "Bangalore",
        "openings": 3,
        "min_score": 65.0,
        "min_cgpa": 8.0,
        "branches": "AIML",
        "description": "Optimize deep learning training and inference on NVIDIA GPU hardware.",
        "eligibility": "Final year B.Tech, AIML, CGPA >= 8.0",
        "apply_link": "https://nvidia.com/careers",
        "app_start": date(2025, 8, 1),
        "app_end": date(2025, 9, 1),
    },
    {
        "company": "NVIDIA India",
        "title": "GPU Architecture Research Intern",
        "type": "RESEARCH",
        "mode": "ONSITE",
        "stipend": 95000,
        "duration": "3 months",
        "location": "Bangalore",
        "openings": 2,
        "min_score": 70.0,
        "min_cgpa": 8.5,
        "branches": "AIML,ECE",
        "description": "Work on next-generation GPU micro-architecture design and simulation.",
        "eligibility": "Final year B.Tech, AIML or ECE, CGPA >= 8.5",
        "apply_link": "https://nvidia.com/careers",
        "app_start": date(2025, 9, 1),
        "app_end": date(2025, 9, 20),
    },
    {
        "company": "Tata Power",
        "title": "Renewable Energy Systems Intern",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 38000,
        "duration": "3 months",
        "location": "Mumbai",
        "openings": 8,
        "min_score": 35.0,
        "min_cgpa": 6.5,
        "branches": "EEE",
        "description": "Support design and O&M of solar and wind energy projects.",
        "eligibility": "3rd/4th year B.Tech, EEE, CGPA >= 6.5",
        "apply_link": "https://www.tatapower.com/careers",
        "app_start": date(2025, 10, 1),
        "app_end": date(2025, 11, 1),
    },
    {
        "company": "Tata Power",
        "title": "Power Electronics Research Intern",
        "type": "RESEARCH",
        "mode": "ONSITE",
        "stipend": 42000,
        "duration": "6 months",
        "location": "Jamshedpur",
        "openings": 4,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "EEE",
        "description": "Research power converter topologies for EV charging infrastructure.",
        "eligibility": "Final year B.Tech, EEE, CGPA >= 7.0",
        "apply_link": "https://www.tatapower.com/careers",
        "app_start": date(2025, 8, 1),
        "app_end": date(2025, 9, 1),
    },
    {
        "company": "Tata Motors",
        "title": "Vehicle Dynamics Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 45000,
        "duration": "6 months",
        "location": "Pune",
        "openings": 5,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "Mechanical",
        "description": "Analyze and improve vehicle ride, handling, and NVH characteristics.",
        "eligibility": "3rd/4th year B.Tech, Mechanical, CGPA >= 7.0",
        "apply_link": "https://careers.tatamotors.com",
        "app_start": date(2025, 9, 1),
        "app_end": date(2025, 10, 1),
    },
    {
        "company": "Tata Motors",
        "title": "EV Battery Systems Intern",
        "type": "RESEARCH",
        "mode": "HYBRID",
        "stipend": 48000,
        "duration": "3 months",
        "location": "Pune",
        "openings": 4,
        "min_score": 45.0,
        "min_cgpa": 7.5,
        "branches": "Mechanical,EEE",
        "description": "Research EV battery thermal management and BMS algorithm development.",
        "eligibility": "3rd/4th year B.Tech, Mechanical or EEE, CGPA >= 7.5",
        "apply_link": "https://careers.tatamotors.com",
        "app_start": date(2025, 11, 1),
        "app_end": date(2025, 12, 1),
    },
    {
        "company": "Mahindra & Mahindra",
        "title": "Product Design Intern",
        "type": "DESIGN",
        "mode": "ONSITE",
        "stipend": 40000,
        "duration": "6 months",
        "location": "Nashik",
        "openings": 6,
        "min_score": 35.0,
        "min_cgpa": 7.0,
        "branches": "Mechanical",
        "description": "Design and develop mechanical sub-assemblies for utility vehicles.",
        "eligibility": "3rd/4th year B.Tech, Mechanical, CGPA >= 7.0",
        "apply_link": "https://careers.mahindra.com",
        "app_start": date(2025, 8, 15),
        "app_end": date(2025, 9, 15),
    },
    {
        "company": "Mahindra & Mahindra",
        "title": "Manufacturing Engineering Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 38000,
        "duration": "3 months",
        "location": "Chakan, Pune",
        "openings": 8,
        "min_score": 30.0,
        "min_cgpa": 6.5,
        "branches": "Mechanical",
        "description": "Optimize manufacturing processes in the vehicle assembly plant.",
        "eligibility": "3rd/4th year B.Tech, Mechanical, CGPA >= 6.5",
        "apply_link": "https://careers.mahindra.com",
        "app_start": date(2025, 10, 1),
        "app_end": date(2025, 11, 1),
    },
    {
        "company": "ISRO VSSC",
        "title": "Propulsion Systems Research Intern",
        "type": "RESEARCH",
        "mode": "ONSITE",
        "stipend": 25000,
        "duration": "2 months",
        "location": "Thiruvananthapuram",
        "openings": 5,
        "min_score": 50.0,
        "min_cgpa": 8.0,
        "branches": "Mechanical",
        "description": "Assist in design analysis of solid and liquid propulsion systems for launch vehicles.",
        "eligibility": "Final year B.Tech, Mechanical, CGPA >= 8.0",
        "apply_link": "https://www.isro.gov.in/careers",
        "app_start": date(2025, 6, 1),
        "app_end": date(2025, 7, 1),
    },
    {
        "company": "ISRO VSSC",
        "title": "Electronics & Control Systems Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 25000,
        "duration": "2 months",
        "location": "Thiruvananthapuram",
        "openings": 4,
        "min_score": 50.0,
        "min_cgpa": 8.0,
        "branches": "ECE,EEE",
        "description": "Work on avionics hardware and flight control software for ISRO missions.",
        "eligibility": "Final year B.Tech, ECE or EEE, CGPA >= 8.0",
        "apply_link": "https://www.isro.gov.in/careers",
        "app_start": date(2025, 6, 1),
        "app_end": date(2025, 7, 1),
    },
    {
        "company": "Wipro Technologies",
        "title": "ML Engineering Intern",
        "type": "TECHNICAL",
        "mode": "HYBRID",
        "stipend": 35000,
        "duration": "3 months",
        "location": "Bangalore",
        "openings": 20,
        "min_score": 25.0,
        "min_cgpa": 6.5,
        "branches": "AIML",
        "description": "Build and deploy ML models for Wipro's enterprise AI platform.",
        "eligibility": "3rd/4th year B.Tech, AIML, CGPA >= 6.5",
        "apply_link": "https://careers.wipro.com",
        "app_start": date(2025, 9, 1),
        "app_end": date(2025, 10, 1),
    },
    {
        "company": "Wipro Technologies",
        "title": "Cloud DevOps Intern",
        "type": "TECHNICAL",
        "mode": "REMOTE",
        "stipend": 30000,
        "duration": "3 months",
        "location": "Remote",
        "openings": 15,
        "min_score": 20.0,
        "min_cgpa": 6.0,
        "branches": None,
        "description": "Automate CI/CD pipelines and manage Kubernetes clusters for enterprise clients.",
        "eligibility": "Any branch, 3rd/4th year B.Tech, CGPA >= 6.0",
        "apply_link": "https://careers.wipro.com",
        "app_start": date(2025, 10, 1),
        "app_end": date(2025, 11, 1),
    },
]

# Pad to 50 if needed (already 46 above — add 4 more)
INTERNSHIP_SEED += [
    {
        "company": "Google India",
        "title": "Product Management Intern",
        "type": "MANAGEMENT",
        "mode": "HYBRID",
        "stipend": 75000,
        "duration": "3 months",
        "location": "Bangalore",
        "openings": 3,
        "min_score": 55.0,
        "min_cgpa": 7.5,
        "branches": "AIML",
        "description": "Work alongside Google PMs to define product strategy for Indian market features.",
        "eligibility": "Final year B.Tech, AIML, CGPA >= 7.5",
        "apply_link": "https://careers.google.com/india",
        "app_start": date(2025, 12, 1),
        "app_end": date(2025, 12, 31),
    },
    {
        "company": "Qualcomm India",
        "title": "5G Modem Software Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 60000,
        "duration": "3 months",
        "location": "Bangalore",
        "openings": 4,
        "min_score": 55.0,
        "min_cgpa": 7.5,
        "branches": "ECE",
        "description": "Develop 5G NR Layer 2 protocol software for Qualcomm's modem team.",
        "eligibility": "Final year B.Tech, ECE, CGPA >= 7.5",
        "apply_link": "https://www.qualcomm.com/careers",
        "app_start": date(2025, 8, 15),
        "app_end": date(2025, 9, 15),
    },
    {
        "company": "ABB India",
        "title": "Robotics Integration Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 44000,
        "duration": "6 months",
        "location": "Bangalore",
        "openings": 4,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "Mechanical,EEE",
        "description": "Program and integrate ABB industrial robots for automotive assembly applications.",
        "eligibility": "3rd/4th year B.Tech, Mechanical or EEE, CGPA >= 7.0",
        "apply_link": "https://new.abb.com/careers/india",
        "app_start": date(2025, 11, 15),
        "app_end": date(2025, 12, 15),
    },
    {
        "company": "Texas Instruments India",
        "title": "Power Management IC Design Intern",
        "type": "TECHNICAL",
        "mode": "ONSITE",
        "stipend": 58000,
        "duration": "3 months",
        "location": "Bangalore",
        "openings": 3,
        "min_score": 55.0,
        "min_cgpa": 8.0,
        "branches": "ECE,EEE",
        "description": "Design and simulate advanced PMIC circuits for battery-powered IoT applications.",
        "eligibility": "Final year B.Tech, ECE or EEE, CGPA >= 8.0",
        "apply_link": "https://careers.ti.com",
        "app_start": date(2025, 12, 1),
        "app_end": date(2025, 12, 31),
    },
]


# ─── PLACEMENT JOBS (50) ──────────────────────────────────────────────────────

PLACEMENT_SEED = [
    # ── Google ────────────────────────────────────────────────────────────────
    {
        "company": "Google India",
        "title": "Software Engineer – AI/ML",
        "pkg_min": 24.0, "pkg_max": 40.0,
        "location": "Bangalore",
        "openings": 5,
        "min_score": 70.0,
        "min_cgpa": 8.5,
        "branches": "AIML",
        "description": "Design and build ML-powered products used by billions of Google users.",
        "eligibility": "B.Tech/B.E. AIML, CGPA >= 8.5, Readiness >= 70",
        "apply_link": "https://careers.google.com/india",
        "deadline": date(2025, 10, 31),
        "bond": None,
    },
    {
        "company": "Google India",
        "title": "Data Engineer",
        "pkg_min": 22.0, "pkg_max": 35.0,
        "location": "Hyderabad",
        "openings": 3,
        "min_score": 65.0,
        "min_cgpa": 8.0,
        "branches": "AIML",
        "description": "Build large-scale data infrastructure and real-time analytics pipelines.",
        "eligibility": "B.Tech/B.E. AIML, CGPA >= 8.0",
        "apply_link": "https://careers.google.com/india",
        "deadline": date(2025, 11, 15),
        "bond": None,
    },
    # ── Microsoft ─────────────────────────────────────────────────────────────
    {
        "company": "Microsoft",
        "title": "Software Development Engineer",
        "pkg_min": 20.0, "pkg_max": 32.0,
        "location": "Hyderabad",
        "openings": 8,
        "min_score": 60.0,
        "min_cgpa": 8.0,
        "branches": "AIML",
        "description": "Build products for Azure, Office 365, and Microsoft's cloud ecosystem.",
        "eligibility": "B.Tech AIML, CGPA >= 8.0",
        "apply_link": "https://careers.microsoft.com/india",
        "deadline": date(2025, 10, 15),
        "bond": None,
    },
    {
        "company": "Microsoft",
        "title": "Azure Cloud Solutions Engineer",
        "pkg_min": 18.0, "pkg_max": 28.0,
        "location": "Bangalore",
        "openings": 5,
        "min_score": 55.0,
        "min_cgpa": 7.5,
        "branches": "AIML",
        "description": "Design, deploy, and support Azure cloud solutions for enterprise customers.",
        "eligibility": "B.Tech AIML, CGPA >= 7.5",
        "apply_link": "https://careers.microsoft.com/india",
        "deadline": date(2025, 11, 30),
        "bond": None,
    },
    # ── Amazon ────────────────────────────────────────────────────────────────
    {
        "company": "Amazon Web Services India",
        "title": "Cloud Support Engineer",
        "pkg_min": 14.0, "pkg_max": 22.0,
        "location": "Hyderabad",
        "openings": 15,
        "min_score": 50.0,
        "min_cgpa": 7.5,
        "branches": "AIML",
        "description": "Provide technical support for AWS cloud services to enterprise customers.",
        "eligibility": "B.Tech AIML, CGPA >= 7.5",
        "apply_link": "https://amazon.jobs/india",
        "deadline": date(2025, 10, 31),
        "bond": None,
    },
    {
        "company": "Amazon Web Services India",
        "title": "ML Engineer – SageMaker",
        "pkg_min": 18.0, "pkg_max": 30.0,
        "location": "Bangalore",
        "openings": 5,
        "min_score": 60.0,
        "min_cgpa": 8.0,
        "branches": "AIML",
        "description": "Build and scale ML infrastructure on AWS SageMaker for enterprise ML teams.",
        "eligibility": "B.Tech AIML, CGPA >= 8.0",
        "apply_link": "https://amazon.jobs/india",
        "deadline": date(2025, 12, 15),
        "bond": None,
    },
    # ── Qualcomm ──────────────────────────────────────────────────────────────
    {
        "company": "Qualcomm India",
        "title": "Staff Engineer – VLSI Design",
        "pkg_min": 14.0, "pkg_max": 22.0,
        "location": "Bangalore",
        "openings": 6,
        "min_score": 60.0,
        "min_cgpa": 7.5,
        "branches": "ECE",
        "description": "Contribute to RTL design and verification of 5G modem SoCs.",
        "eligibility": "B.Tech ECE, CGPA >= 7.5",
        "apply_link": "https://www.qualcomm.com/careers",
        "deadline": date(2025, 9, 30),
        "bond": None,
    },
    {
        "company": "Qualcomm India",
        "title": "Embedded Software Engineer",
        "pkg_min": 12.0, "pkg_max": 18.0,
        "location": "Hyderabad",
        "openings": 8,
        "min_score": 55.0,
        "min_cgpa": 7.0,
        "branches": "ECE",
        "description": "Develop firmware for Qualcomm's IoT and mobile platforms.",
        "eligibility": "B.Tech ECE, CGPA >= 7.0",
        "apply_link": "https://www.qualcomm.com/careers",
        "deadline": date(2025, 10, 31),
        "bond": None,
    },
    {
        "company": "Qualcomm India",
        "title": "RF Systems Engineer",
        "pkg_min": 14.0, "pkg_max": 20.0,
        "location": "Bangalore",
        "openings": 4,
        "min_score": 60.0,
        "min_cgpa": 8.0,
        "branches": "ECE",
        "description": "Design and validate RF front-end modules for 5G mmWave devices.",
        "eligibility": "B.Tech ECE, CGPA >= 8.0",
        "apply_link": "https://www.qualcomm.com/careers",
        "deadline": date(2025, 11, 15),
        "bond": None,
    },
    # ── Intel ─────────────────────────────────────────────────────────────────
    {
        "company": "Intel India",
        "title": "FPGA Design Engineer",
        "pkg_min": 12.0, "pkg_max": 18.0,
        "location": "Bangalore",
        "openings": 5,
        "min_score": 55.0,
        "min_cgpa": 7.5,
        "branches": "ECE",
        "description": "Design high-performance FPGA systems for AI and data center acceleration.",
        "eligibility": "B.Tech ECE, CGPA >= 7.5",
        "apply_link": "https://jobs.intel.com/india",
        "deadline": date(2025, 10, 15),
        "bond": None,
    },
    {
        "company": "Intel India",
        "title": "AI Hardware Engineer",
        "pkg_min": 16.0, "pkg_max": 24.0,
        "location": "Bangalore",
        "openings": 4,
        "min_score": 65.0,
        "min_cgpa": 8.0,
        "branches": "AIML,ECE",
        "description": "Optimize neural network performance on Intel's Gaudi and Xe GPU hardware.",
        "eligibility": "B.Tech AIML or ECE, CGPA >= 8.0",
        "apply_link": "https://jobs.intel.com/india",
        "deadline": date(2025, 12, 1),
        "bond": None,
    },
    # ── Texas Instruments ─────────────────────────────────────────────────────
    {
        "company": "Texas Instruments India",
        "title": "Analog Design Engineer",
        "pkg_min": 11.0, "pkg_max": 16.0,
        "location": "Bangalore",
        "openings": 6,
        "min_score": 55.0,
        "min_cgpa": 7.5,
        "branches": "ECE,EEE",
        "description": "Design mixed-signal ICs for industrial, automotive, and communication markets.",
        "eligibility": "B.Tech ECE or EEE, CGPA >= 7.5",
        "apply_link": "https://careers.ti.com",
        "deadline": date(2025, 9, 30),
        "bond": None,
    },
    {
        "company": "Texas Instruments India",
        "title": "Applications Engineer",
        "pkg_min": 9.0, "pkg_max": 14.0,
        "location": "Bangalore",
        "openings": 8,
        "min_score": 45.0,
        "min_cgpa": 7.0,
        "branches": "ECE,EEE",
        "description": "Provide technical support and design solutions for TI's global customer base.",
        "eligibility": "B.Tech ECE or EEE, CGPA >= 7.0",
        "apply_link": "https://careers.ti.com",
        "deadline": date(2025, 10, 31),
        "bond": None,
    },
    # ── ABB ───────────────────────────────────────────────────────────────────
    {
        "company": "ABB India",
        "title": "Graduate Engineer Trainee – Power",
        "pkg_min": 6.5, "pkg_max": 9.0,
        "location": "Bangalore",
        "openings": 15,
        "min_score": 40.0,
        "min_cgpa": 6.5,
        "branches": "EEE",
        "description": "1-year rotational programme across ABB's power products and grid divisions.",
        "eligibility": "B.Tech EEE, CGPA >= 6.5",
        "apply_link": "https://new.abb.com/careers/india",
        "deadline": date(2025, 10, 1),
        "bond": "2-year service bond",
    },
    {
        "company": "ABB India",
        "title": "Automation & Robotics Engineer",
        "pkg_min": 8.0, "pkg_max": 12.0,
        "location": "Nashik",
        "openings": 8,
        "min_score": 45.0,
        "min_cgpa": 7.0,
        "branches": "Mechanical,EEE",
        "description": "Program and maintain ABB industrial robots for automotive manufacturing lines.",
        "eligibility": "B.Tech Mechanical or EEE, CGPA >= 7.0",
        "apply_link": "https://new.abb.com/careers/india",
        "deadline": date(2025, 11, 15),
        "bond": None,
    },
    # ── Siemens ───────────────────────────────────────────────────────────────
    {
        "company": "Siemens India",
        "title": "Graduate Trainee – Digital Industries",
        "pkg_min": 7.0, "pkg_max": 10.0,
        "location": "Pune",
        "openings": 12,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "EEE,Mechanical",
        "description": "Work across Siemens' digital factory, automation, and drives product lines.",
        "eligibility": "B.Tech EEE or Mechanical, CGPA >= 7.0",
        "apply_link": "https://www.siemens.co.in/careers",
        "deadline": date(2025, 10, 31),
        "bond": "2-year service bond",
    },
    {
        "company": "Siemens India",
        "title": "Electrical Systems Engineer",
        "pkg_min": 9.0, "pkg_max": 14.0,
        "location": "Mumbai",
        "openings": 6,
        "min_score": 45.0,
        "min_cgpa": 7.5,
        "branches": "EEE",
        "description": "Design and commission switchgear and protection relay systems for power utilities.",
        "eligibility": "B.Tech EEE, CGPA >= 7.5",
        "apply_link": "https://www.siemens.co.in/careers",
        "deadline": date(2025, 11, 30),
        "bond": None,
    },
    # ── Bosch ─────────────────────────────────────────────────────────────────
    {
        "company": "Bosch India",
        "title": "Graduate Engineer – Embedded Systems",
        "pkg_min": 8.0, "pkg_max": 12.0,
        "location": "Bangalore",
        "openings": 15,
        "min_score": 50.0,
        "min_cgpa": 7.0,
        "branches": "ECE,EEE",
        "description": "Develop automotive ECU firmware using C/C++ and AUTOSAR standards.",
        "eligibility": "B.Tech ECE or EEE, CGPA >= 7.0",
        "apply_link": "https://www.bosch.in/careers",
        "deadline": date(2025, 9, 30),
        "bond": None,
    },
    {
        "company": "Bosch India",
        "title": "Mechanical Design Engineer – Automotive",
        "pkg_min": 7.5, "pkg_max": 11.0,
        "location": "Coimbatore",
        "openings": 10,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "Mechanical",
        "description": "Design, analyse, and validate automotive components using CAD and FEA tools.",
        "eligibility": "B.Tech Mechanical, CGPA >= 7.0",
        "apply_link": "https://www.bosch.in/careers",
        "deadline": date(2025, 10, 31),
        "bond": None,
    },
    {
        "company": "Bosch India",
        "title": "ADAS Algorithm Engineer",
        "pkg_min": 12.0, "pkg_max": 18.0,
        "location": "Bangalore",
        "openings": 5,
        "min_score": 60.0,
        "min_cgpa": 8.0,
        "branches": "AIML,ECE",
        "description": "Develop computer vision and sensor fusion algorithms for ADAS systems.",
        "eligibility": "B.Tech AIML or ECE, CGPA >= 8.0",
        "apply_link": "https://www.bosch.in/careers",
        "deadline": date(2025, 12, 1),
        "bond": None,
    },
    # ── Mercedes ──────────────────────────────────────────────────────────────
    {
        "company": "Mercedes-Benz India",
        "title": "Powertrain Engineer",
        "pkg_min": 9.0, "pkg_max": 14.0,
        "location": "Pune",
        "openings": 6,
        "min_score": 50.0,
        "min_cgpa": 7.5,
        "branches": "Mechanical",
        "description": "Develop and validate engine and transmission systems for Mercedes-Benz India.",
        "eligibility": "B.Tech Mechanical, CGPA >= 7.5",
        "apply_link": "https://www.mercedes-benz.co.in/careers",
        "deadline": date(2025, 10, 15),
        "bond": None,
    },
    {
        "company": "Mercedes-Benz India",
        "title": "Quality Assurance Engineer",
        "pkg_min": 8.0, "pkg_max": 12.0,
        "location": "Pune",
        "openings": 8,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "Mechanical",
        "description": "Drive quality improvement initiatives across vehicle assembly and supplier parts.",
        "eligibility": "B.Tech Mechanical, CGPA >= 7.0",
        "apply_link": "https://www.mercedes-benz.co.in/careers",
        "deadline": date(2025, 11, 30),
        "bond": None,
    },
    # ── L&T ───────────────────────────────────────────────────────────────────
    {
        "company": "L&T Technology Services",
        "title": "Graduate Engineer Trainee – EEE",
        "pkg_min": 5.5, "pkg_max": 8.0,
        "location": "Chennai",
        "openings": 20,
        "min_score": 30.0,
        "min_cgpa": 6.5,
        "branches": "EEE",
        "description": "Rotational engineer programme in L&T's power, buildings, and heavy civil divisions.",
        "eligibility": "B.Tech EEE, CGPA >= 6.5",
        "apply_link": "https://www.larsentoubro.com/careers",
        "deadline": date(2025, 10, 1),
        "bond": "3-year service bond",
    },
    {
        "company": "L&T Technology Services",
        "title": "Mechanical Design Engineer",
        "pkg_min": 6.0, "pkg_max": 9.0,
        "location": "Vadodara",
        "openings": 15,
        "min_score": 30.0,
        "min_cgpa": 6.5,
        "branches": "Mechanical",
        "description": "Design heavy structural components for LNG plants and refineries using PDS/SP3D.",
        "eligibility": "B.Tech Mechanical, CGPA >= 6.5",
        "apply_link": "https://www.larsentoubro.com/careers",
        "deadline": date(2025, 10, 31),
        "bond": "3-year service bond",
    },
    # ── Infosys ───────────────────────────────────────────────────────────────
    {
        "company": "Infosys BPM",
        "title": "Systems Engineer",
        "pkg_min": 4.5, "pkg_max": 6.5,
        "location": "Bangalore",
        "openings": 100,
        "min_score": 20.0,
        "min_cgpa": 6.0,
        "branches": None,
        "description": "Work across full-stack development, testing, and application support projects.",
        "eligibility": "Any B.Tech branch, CGPA >= 6.0",
        "apply_link": "https://www.infosys.com/careers/india",
        "deadline": date(2025, 10, 31),
        "bond": "1-year service bond",
    },
    {
        "company": "Infosys BPM",
        "title": "Data Scientist",
        "pkg_min": 7.0, "pkg_max": 12.0,
        "location": "Pune",
        "openings": 20,
        "min_score": 35.0,
        "min_cgpa": 7.0,
        "branches": "AIML",
        "description": "Build ML models and data pipelines for Infosys's global analytics practice.",
        "eligibility": "B.Tech AIML, CGPA >= 7.0",
        "apply_link": "https://www.infosys.com/careers/india",
        "deadline": date(2025, 11, 30),
        "bond": None,
    },
    # ── TCS ───────────────────────────────────────────────────────────────────
    {
        "company": "Tata Consultancy Services",
        "title": "IT Analyst",
        "pkg_min": 4.0, "pkg_max": 6.0,
        "location": "Mumbai",
        "openings": 150,
        "min_score": 15.0,
        "min_cgpa": 6.0,
        "branches": None,
        "description": "Work on enterprise application development and maintenance for global clients.",
        "eligibility": "Any B.Tech branch, CGPA >= 6.0",
        "apply_link": "https://www.tcs.com/careers",
        "deadline": date(2025, 11, 1),
        "bond": "2-year service bond",
    },
    {
        "company": "Tata Consultancy Services",
        "title": "IoT Platform Engineer",
        "pkg_min": 6.5, "pkg_max": 10.0,
        "location": "Hyderabad",
        "openings": 20,
        "min_score": 35.0,
        "min_cgpa": 6.5,
        "branches": "ECE,EEE,AIML",
        "description": "Develop and integrate TCS's Industrial IoT platform for manufacturing clients.",
        "eligibility": "B.Tech ECE, EEE, or AIML, CGPA >= 6.5",
        "apply_link": "https://www.tcs.com/careers",
        "deadline": date(2025, 12, 1),
        "bond": None,
    },
    # ── Accenture ─────────────────────────────────────────────────────────────
    {
        "company": "Accenture India",
        "title": "AI Engineer",
        "pkg_min": 7.0, "pkg_max": 12.0,
        "location": "Bangalore",
        "openings": 30,
        "min_score": 35.0,
        "min_cgpa": 7.0,
        "branches": "AIML",
        "description": "Implement AI and automation solutions for Accenture's enterprise clients.",
        "eligibility": "B.Tech AIML, CGPA >= 7.0",
        "apply_link": "https://www.accenture.com/in-en/careers",
        "deadline": date(2025, 10, 15),
        "bond": None,
    },
    {
        "company": "Accenture India",
        "title": "Embedded Systems Engineer",
        "pkg_min": 6.5, "pkg_max": 10.0,
        "location": "Bangalore",
        "openings": 20,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "ECE,EEE",
        "description": "Develop embedded software solutions for industrial IoT and automotive clients.",
        "eligibility": "B.Tech ECE or EEE, CGPA >= 7.0",
        "apply_link": "https://www.accenture.com/in-en/careers",
        "deadline": date(2025, 11, 15),
        "bond": None,
    },
    # Extra placements to reach 50
    {
        "company": "NVIDIA India",
        "title": "Deep Learning Engineer",
        "pkg_min": 20.0, "pkg_max": 35.0,
        "location": "Bangalore",
        "openings": 4,
        "min_score": 70.0,
        "min_cgpa": 8.5,
        "branches": "AIML",
        "description": "Build and optimize DL training frameworks for NVIDIA's GPU products.",
        "eligibility": "B.Tech AIML, CGPA >= 8.5",
        "apply_link": "https://nvidia.com/careers",
        "deadline": date(2025, 9, 30),
        "bond": None,
    },
    {
        "company": "Tata Power",
        "title": "Power Systems Engineer",
        "pkg_min": 6.0, "pkg_max": 9.0,
        "location": "Mumbai",
        "openings": 10,
        "min_score": 35.0,
        "min_cgpa": 7.0,
        "branches": "EEE",
        "description": "Operate and maintain thermal, hydro, and renewable power generation assets.",
        "eligibility": "B.Tech EEE, CGPA >= 7.0",
        "apply_link": "https://www.tatapower.com/careers",
        "deadline": date(2025, 10, 31),
        "bond": None,
    },
    {
        "company": "Tata Motors",
        "title": "Vehicle Testing Engineer",
        "pkg_min": 6.5, "pkg_max": 9.5,
        "location": "Pune",
        "openings": 8,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "Mechanical",
        "description": "Conduct performance, endurance, and reliability testing of Tata commercial vehicles.",
        "eligibility": "B.Tech Mechanical, CGPA >= 7.0",
        "apply_link": "https://careers.tatamotors.com",
        "deadline": date(2025, 10, 15),
        "bond": None,
    },
    {
        "company": "Tata Motors",
        "title": "EV Software Engineer",
        "pkg_min": 9.0, "pkg_max": 15.0,
        "location": "Pune",
        "openings": 6,
        "min_score": 55.0,
        "min_cgpa": 7.5,
        "branches": "AIML,ECE",
        "description": "Develop BMS and ADAS software for Tata's electric vehicle platform.",
        "eligibility": "B.Tech AIML or ECE, CGPA >= 7.5",
        "apply_link": "https://careers.tatamotors.com",
        "deadline": date(2025, 11, 30),
        "bond": None,
    },
    {
        "company": "Mahindra & Mahindra",
        "title": "Design Engineer – Structures",
        "pkg_min": 6.0, "pkg_max": 9.0,
        "location": "Nashik",
        "openings": 10,
        "min_score": 35.0,
        "min_cgpa": 7.0,
        "branches": "Mechanical",
        "description": "Design and validate vehicle chassis, frame, and body-in-white structural components.",
        "eligibility": "B.Tech Mechanical, CGPA >= 7.0",
        "apply_link": "https://careers.mahindra.com",
        "deadline": date(2025, 9, 30),
        "bond": None,
    },
    {
        "company": "Mahindra & Mahindra",
        "title": "Manufacturing Engineer",
        "pkg_min": 5.5, "pkg_max": 8.0,
        "location": "Chakan, Pune",
        "openings": 12,
        "min_score": 30.0,
        "min_cgpa": 6.5,
        "branches": "Mechanical",
        "description": "Optimize production processes and implement lean manufacturing at Mahindra plants.",
        "eligibility": "B.Tech Mechanical, CGPA >= 6.5",
        "apply_link": "https://careers.mahindra.com",
        "deadline": date(2025, 10, 31),
        "bond": None,
    },
    {
        "company": "ISRO VSSC",
        "title": "Scientist/Engineer SC – Mechanical",
        "pkg_min": 7.0, "pkg_max": 10.0,
        "location": "Thiruvananthapuram",
        "openings": 5,
        "min_score": 55.0,
        "min_cgpa": 8.0,
        "branches": "Mechanical",
        "description": "Work on structural design and analysis of satellite launch vehicle components.",
        "eligibility": "B.Tech Mechanical, CGPA >= 8.0",
        "apply_link": "https://www.isro.gov.in/careers",
        "deadline": date(2025, 8, 31),
        "bond": "5-year government service",
    },
    {
        "company": "ISRO VSSC",
        "title": "Scientist/Engineer SC – Electronics",
        "pkg_min": 7.0, "pkg_max": 10.0,
        "location": "Thiruvananthapuram",
        "openings": 4,
        "min_score": 55.0,
        "min_cgpa": 8.0,
        "branches": "ECE,EEE",
        "description": "Develop and test avionics and telemetry systems for ISRO launch vehicles.",
        "eligibility": "B.Tech ECE or EEE, CGPA >= 8.0",
        "apply_link": "https://www.isro.gov.in/careers",
        "deadline": date(2025, 8, 31),
        "bond": "5-year government service",
    },
    {
        "company": "Wipro Technologies",
        "title": "AI/ML Engineer",
        "pkg_min": 7.0, "pkg_max": 12.0,
        "location": "Hyderabad",
        "openings": 30,
        "min_score": 35.0,
        "min_cgpa": 7.0,
        "branches": "AIML",
        "description": "Build AI-powered products for Wipro's enterprise clients across industries.",
        "eligibility": "B.Tech AIML, CGPA >= 7.0",
        "apply_link": "https://careers.wipro.com",
        "deadline": date(2025, 11, 1),
        "bond": None,
    },
    {
        "company": "Wipro Technologies",
        "title": "Embedded Engineer",
        "pkg_min": 5.5, "pkg_max": 8.5,
        "location": "Bangalore",
        "openings": 20,
        "min_score": 30.0,
        "min_cgpa": 6.5,
        "branches": "ECE,EEE",
        "description": "Develop embedded C firmware and device drivers for industrial and automotive clients.",
        "eligibility": "B.Tech ECE or EEE, CGPA >= 6.5",
        "apply_link": "https://careers.wipro.com",
        "deadline": date(2025, 11, 30),
        "bond": None,
    },
    {
        "company": "Amazon Web Services India",
        "title": "Solutions Architect",
        "pkg_min": 22.0, "pkg_max": 38.0,
        "location": "Delhi",
        "openings": 3,
        "min_score": 65.0,
        "min_cgpa": 8.0,
        "branches": "AIML",
        "description": "Design scalable AWS cloud solutions and present architectures to enterprise CXOs.",
        "eligibility": "B.Tech AIML, CGPA >= 8.0",
        "apply_link": "https://amazon.jobs/india",
        "deadline": date(2025, 12, 31),
        "bond": None,
    },
    {
        "company": "Google India",
        "title": "Site Reliability Engineer",
        "pkg_min": 22.0, "pkg_max": 38.0,
        "location": "Hyderabad",
        "openings": 3,
        "min_score": 70.0,
        "min_cgpa": 8.5,
        "branches": "AIML",
        "description": "Maintain and scale Google's production infrastructure with 99.99% uptime.",
        "eligibility": "B.Tech AIML, CGPA >= 8.5",
        "apply_link": "https://careers.google.com/india",
        "deadline": date(2025, 10, 15),
        "bond": None,
    },
    {
        "company": "Bosch India",
        "title": "Power Electronics Engineer",
        "pkg_min": 9.0, "pkg_max": 14.0,
        "location": "Bangalore",
        "openings": 6,
        "min_score": 50.0,
        "min_cgpa": 7.5,
        "branches": "EEE",
        "description": "Design power converters and inverters for EV charging and energy storage systems.",
        "eligibility": "B.Tech EEE, CGPA >= 7.5",
        "apply_link": "https://www.bosch.in/careers",
        "deadline": date(2025, 11, 15),
        "bond": None,
    },
    {
        "company": "Texas Instruments India",
        "title": "Verification Engineer",
        "pkg_min": 12.0, "pkg_max": 17.0,
        "location": "Bangalore",
        "openings": 5,
        "min_score": 55.0,
        "min_cgpa": 7.5,
        "branches": "ECE",
        "description": "Develop UVM-based verification environments for TI's analog mixed-signal ICs.",
        "eligibility": "B.Tech ECE, CGPA >= 7.5",
        "apply_link": "https://careers.ti.com",
        "deadline": date(2025, 10, 15),
        "bond": None,
    },
    {
        "company": "Tata Consultancy Services",
        "title": "Embedded Systems Analyst",
        "pkg_min": 6.5, "pkg_max": 9.5,
        "location": "Chennai",
        "openings": 25,
        "min_score": 35.0,
        "min_cgpa": 6.5,
        "branches": "ECE,EEE",
        "description": "Develop firmware solutions for industrial control and automotive clients.",
        "eligibility": "B.Tech ECE or EEE, CGPA >= 6.5",
        "apply_link": "https://www.tcs.com/careers",
        "deadline": date(2025, 11, 15),
        "bond": None,
    },
    {
        "company": "Siemens India",
        "title": "Process Automation Engineer",
        "pkg_min": 7.5, "pkg_max": 11.0,
        "location": "Pune",
        "openings": 10,
        "min_score": 40.0,
        "min_cgpa": 7.0,
        "branches": "EEE,Mechanical",
        "description": "Design SCADA and DCS automation systems for Siemens' process industry clients.",
        "eligibility": "B.Tech EEE or Mechanical, CGPA >= 7.0",
        "apply_link": "https://www.siemens.co.in/careers",
        "deadline": date(2025, 12, 1),
        "bond": None,
    },
]
