"""
Industry Intelligence Engine seed data.

15 companies across 4 GITAM CareerHub branches:
AIML, ECE, EEE, Mechanical.

Each company includes:
- Company profile (name, industry, size, HQ, URLs)
- Job roles (entry-level / trainee positions)
- Required skills with weightage
- Recommended courses, projects, certifications
- Interview rounds + question bank
"""

COMPANY_SEED = [
    # ─── AIML-focused ────────────────────────────────────────────────────────
    {
        "name": "Google India",
        "industry": "Technology",
        "headquarters": "Bengaluru, Karnataka",
        "description": "Google India develops Search, Cloud, Maps, and AI products for the Indian market. Hires top AI/ML talent through campus programs and internships.",
        "company_size": "10,000+ employees",
        "website": "https://careers.google.com",
        "careers_url": "https://careers.google.com/students/",
        "linkedin_url": "https://www.linkedin.com/company/google",
        "is_hiring": True,
        "job_roles": [
            {"title": "Associate Software Engineer - ML", "category": "AI/ML", "type": "FULL_TIME", "level": "ENTRY_LEVEL", "sal_min": 12.0, "sal_max": 20.0, "location": "Bengaluru"},
            {"title": "ML Intern", "category": "AI/ML", "type": "INTERNSHIP", "level": "ENTRY_LEVEL", "sal_min": 5.0, "sal_max": 8.0, "location": "Bengaluru"},
        ],
        "skills": [
            ("Python", "ADVANCED", 2.0),
            ("Machine Learning", "ADVANCED", 2.5),
            ("TensorFlow", "ADVANCED", 2.0),
            ("Data Structures", "ADVANCED", 1.5),
        ],
        "rec_courses": ["Python for AI & Data Science", "Deep Learning with TensorFlow"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Online Coding Round", "order": 1, "desc": "2 DSA problems on Google coding platform. Focus: arrays, graphs, DP."},
            {"name": "Technical Interview 1", "order": 2, "desc": "45-min system design + ML fundamentals."},
            {"name": "Technical Interview 2", "order": 3, "desc": "ML case study: model selection, training, deployment."},
            {"name": "Hiring Committee Review", "order": 4, "desc": "Culture fit and leadership discussion."},
        ],
        "interview_qs": [
            {"q": "Explain the difference between supervised and unsupervised learning with real examples.", "diff": "EASY", "cat": "TECHNICAL", "ans": "Supervised: labeled data (spam detection). Unsupervised: no labels (customer segmentation)."},
            {"q": "How does backpropagation work in neural networks?", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "Chain rule of differentiation applied backward from loss to update weights."},
            {"q": "Design a system to detect fake news using NLP.", "diff": "HARD", "cat": "SYSTEM_DESIGN", "ans": "Data collection → text preprocessing → BERT embeddings → classification → feedback loop."},
        ],
        "branches": ["AIML"],
    },
    {
        "name": "Amazon Web Services India",
        "industry": "Cloud Computing",
        "headquarters": "Mumbai, Maharashtra",
        "description": "AWS India provides cloud infrastructure and AI services. Offers Graduate Engineer Trainee and Intern programs in AI, cloud, and data engineering.",
        "company_size": "5,000-10,000 employees",
        "website": "https://aws.amazon.com",
        "careers_url": "https://www.amazon.jobs/en/locations/india",
        "linkedin_url": "https://www.linkedin.com/company/amazon-web-services",
        "is_hiring": True,
        "job_roles": [
            {"title": "Cloud Support Engineer", "category": "Cloud", "type": "FULL_TIME", "level": "ENTRY_LEVEL", "sal_min": 8.0, "sal_max": 14.0, "location": "Hyderabad"},
            {"title": "Data Engineer Trainee", "category": "AI/ML", "type": "TRAINEE", "level": "ENTRY_LEVEL", "sal_min": 7.0, "sal_max": 10.0, "location": "Bengaluru"},
        ],
        "skills": [
            ("Python", "INTERMEDIATE", 1.5),
            ("Machine Learning", "INTERMEDIATE", 1.5),
            ("Data Structures", "ADVANCED", 2.0),
        ],
        "rec_courses": ["Machine Learning Fundamentals"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Online Assessment", "order": 1, "desc": "Coding + logical reasoning (90 min)."},
            {"name": "Technical Phone Screen", "order": 2, "desc": "ML/Python technical questions."},
            {"name": "Loop Interview (3 rounds)", "order": 3, "desc": "Amazon Leadership Principles + technical depth."},
        ],
        "interview_qs": [
            {"q": "What is overfitting? How do you prevent it?", "diff": "EASY", "cat": "TECHNICAL", "ans": "Overfitting: model memorizes training data. Prevention: regularization, dropout, cross-validation, more data."},
            {"q": "Explain the CAP theorem in distributed systems.", "diff": "HARD", "cat": "SYSTEM_DESIGN", "ans": "Consistency, Availability, Partition-tolerance — only 2 can be guaranteed simultaneously."},
        ],
        "branches": ["AIML"],
    },
    {
        "name": "NVIDIA India",
        "industry": "Semiconductors & AI",
        "headquarters": "Pune, Maharashtra",
        "description": "NVIDIA India develops GPU-accelerated AI and Deep Learning frameworks. Hires AI researchers and computer vision engineers.",
        "company_size": "1,000-5,000 employees",
        "website": "https://www.nvidia.com/en-in/",
        "careers_url": "https://www.nvidia.com/en-us/about-nvidia/careers/",
        "linkedin_url": "https://www.linkedin.com/company/nvidia",
        "is_hiring": True,
        "job_roles": [
            {"title": "AI Research Intern", "category": "AI/ML", "type": "INTERNSHIP", "level": "ENTRY_LEVEL", "sal_min": 6.0, "sal_max": 9.0, "location": "Pune"},
            {"title": "Deep Learning Engineer", "category": "AI/ML", "type": "FULL_TIME", "level": "ENTRY_LEVEL", "sal_min": 14.0, "sal_max": 22.0, "location": "Pune"},
        ],
        "skills": [
            ("TensorFlow", "ADVANCED", 2.5),
            ("Computer Vision", "ADVANCED", 2.5),
            ("Python", "ADVANCED", 2.0),
            ("Machine Learning", "ADVANCED", 2.0),
        ],
        "rec_courses": ["Computer Vision with OpenCV", "Deep Learning with TensorFlow"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Resume Shortlisting", "order": 1, "desc": "GPA > 8.0, strong AI project portfolio."},
            {"name": "Technical Interview - DL", "order": 2, "desc": "Deep learning architecture design, GPU optimization."},
            {"name": "Research Presentation", "order": 3, "desc": "Present a prior project or research paper."},
        ],
        "interview_qs": [
            {"q": "What is the difference between a CNN and an RNN?", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "CNN: spatial feature extraction (images). RNN: sequential data (time series, text)."},
            {"q": "How do you optimize inference speed on a GPU?", "diff": "HARD", "cat": "TECHNICAL", "ans": "TensorRT, quantization, batch processing, pruning, mixed precision training."},
        ],
        "branches": ["AIML"],
    },

    # ─── ECE-focused ─────────────────────────────────────────────────────────
    {
        "name": "Qualcomm India",
        "industry": "Semiconductors",
        "headquarters": "Hyderabad, Telangana",
        "description": "Qualcomm India designs mobile chipsets, wireless modems, and IoT processors. A leading recruiter for ECE students specializing in embedded systems, VLSI, and signal processing.",
        "company_size": "5,000-10,000 employees",
        "website": "https://www.qualcomm.com",
        "careers_url": "https://www.qualcomm.com/company/careers",
        "linkedin_url": "https://www.linkedin.com/company/qualcomm",
        "is_hiring": True,
        "job_roles": [
            {"title": "Embedded Software Engineer", "category": "Embedded", "type": "FULL_TIME", "level": "ENTRY_LEVEL", "sal_min": 10.0, "sal_max": 18.0, "location": "Hyderabad"},
            {"title": "VLSI Design Intern", "category": "VLSI", "type": "INTERNSHIP", "level": "ENTRY_LEVEL", "sal_min": 5.0, "sal_max": 8.0, "location": "Hyderabad"},
        ],
        "skills": [
            ("Embedded C", "ADVANCED", 2.5),
            ("STM32", "INTERMEDIATE", 1.5),
            ("C Programming", "ADVANCED", 2.0),
            ("Digital Electronics", "ADVANCED", 2.0),
            ("Signal Processing", "INTERMEDIATE", 1.5),
        ],
        "rec_courses": ["Embedded Systems with Arduino", "STM32 Microcontroller Programming", "C Programming for Engineers"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Online Aptitude + Coding", "order": 1, "desc": "C/C++ coding, digital electronics MCQs, and aptitude."},
            {"name": "Technical Interview 1 - Embedded", "order": 2, "desc": "RTOS, memory management, microcontroller peripherals."},
            {"name": "Technical Interview 2 - DSP", "order": 3, "desc": "Signal processing, FFT, filters."},
            {"name": "HR Interview", "order": 4, "desc": "Cultural fit, goals, STAR method questions."},
        ],
        "interview_qs": [
            {"q": "What is the difference between a microcontroller and a microprocessor?", "diff": "EASY", "cat": "TECHNICAL", "ans": "Microcontroller has built-in RAM, ROM, I/O. Microprocessor is standalone CPU."},
            {"q": "Explain SPI vs I2C communication protocols.", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "SPI: full-duplex, faster, 4-wire. I2C: half-duplex, 2-wire, multi-master."},
            {"q": "How does a DMA controller work?", "diff": "HARD", "cat": "TECHNICAL", "ans": "DMA transfers data between memory and peripherals without CPU intervention, freeing the processor."},
        ],
        "branches": ["ECE"],
    },
    {
        "name": "Texas Instruments India",
        "industry": "Semiconductors",
        "headquarters": "Bengaluru, Karnataka",
        "description": "Texas Instruments India designs analog ICs, embedded processors, and DSPs. Known for its strong engineering programs for ECE graduates.",
        "company_size": "5,000-10,000 employees",
        "website": "https://www.ti.com",
        "careers_url": "https://careers.ti.com",
        "linkedin_url": "https://www.linkedin.com/company/texas-instruments",
        "is_hiring": True,
        "job_roles": [
            {"title": "Applications Engineer", "category": "Embedded", "type": "FULL_TIME", "level": "ENTRY_LEVEL", "sal_min": 9.0, "sal_max": 15.0, "location": "Bengaluru"},
            {"title": "R&D Intern - Embedded", "category": "Embedded", "type": "INTERNSHIP", "level": "ENTRY_LEVEL", "sal_min": 4.0, "sal_max": 6.0, "location": "Bengaluru"},
        ],
        "skills": [
            ("C Programming", "ADVANCED", 2.0),
            ("Embedded C", "ADVANCED", 2.5),
            ("Signal Processing", "ADVANCED", 2.0),
            ("MATLAB", "INTERMEDIATE", 1.5),
            ("PCB Design", "INTERMEDIATE", 1.0),
        ],
        "rec_courses": ["C Programming for Engineers", "Embedded Systems with Arduino"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Written Test", "order": 1, "desc": "Electronics fundamentals, C programming, signal processing."},
            {"name": "Technical Interview", "order": 2, "desc": "Deep dive into embedded systems, ADC/DAC, timers."},
            {"name": "HR Interview", "order": 3, "desc": "Behavioral questions, career goals."},
        ],
        "interview_qs": [
            {"q": "What is PWM and where is it used?", "diff": "EASY", "cat": "TECHNICAL", "ans": "Pulse Width Modulation: controls duty cycle for motor speed control, LED dimming, etc."},
            {"q": "Explain the difference between ADC and DAC.", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "ADC converts analog signals to digital. DAC converts digital back to analog."},
        ],
        "branches": ["ECE"],
    },
    {
        "name": "Intel India",
        "industry": "Semiconductors",
        "headquarters": "Bengaluru, Karnataka",
        "description": "Intel India focuses on processor design, VLSI, firmware, and AI hardware acceleration. Strong campus hiring program.",
        "company_size": "10,000+ employees",
        "website": "https://www.intel.com/content/www/us/en/jobs/jobs-at-intel.html",
        "careers_url": "https://www.intel.com/content/www/us/en/jobs/jobs-at-intel.html",
        "linkedin_url": "https://www.linkedin.com/company/intel-corporation",
        "is_hiring": True,
        "job_roles": [
            {"title": "Graduate Firmware Engineer", "category": "Embedded", "type": "FULL_TIME", "level": "ENTRY_LEVEL", "sal_min": 11.0, "sal_max": 17.0, "location": "Bengaluru"},
            {"title": "VLSI Physical Design Intern", "category": "VLSI", "type": "INTERNSHIP", "level": "ENTRY_LEVEL", "sal_min": 5.0, "sal_max": 7.0, "location": "Bengaluru"},
        ],
        "skills": [
            ("C Programming", "ADVANCED", 2.0),
            ("Embedded C", "ADVANCED", 2.5),
            ("Digital Electronics", "ADVANCED", 2.0),
            ("Data Structures", "INTERMEDIATE", 1.5),
        ],
        "rec_courses": ["STM32 Microcontroller Programming", "C Programming for Engineers"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Online Assessment", "order": 1, "desc": "C programming, digital electronics, aptitude."},
            {"name": "Technical Phone Interview", "order": 2, "desc": "Embedded C, RTOS, memory layout."},
            {"name": "On-site Technical Rounds (x2)", "order": 3, "desc": "Detailed embedded/VLSI technical discussion."},
        ],
        "interview_qs": [
            {"q": "What is the volatile keyword in C and when should you use it?", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "Tells the compiler not to optimize memory reads — used for hardware registers and shared memory in RTOS."},
            {"q": "Explain the stages of an instruction pipeline.", "diff": "HARD", "cat": "TECHNICAL", "ans": "Fetch → Decode → Execute → Memory → Write-back. Hazards: structural, data, control."},
        ],
        "branches": ["ECE"],
    },

    # ─── EEE-focused ─────────────────────────────────────────────────────────
    {
        "name": "ABB India",
        "industry": "Power & Automation",
        "headquarters": "Bengaluru, Karnataka",
        "description": "ABB India manufactures power equipment, drives, and industrial automation systems. Strong recruiter for EEE graduates in power electronics and PLC automation.",
        "company_size": "5,000-10,000 employees",
        "website": "https://new.abb.com/in",
        "careers_url": "https://careers.abb/in/en",
        "linkedin_url": "https://www.linkedin.com/company/abb",
        "is_hiring": True,
        "job_roles": [
            {"title": "Graduate Engineer Trainee - Power", "category": "Electrical", "type": "TRAINEE", "level": "ENTRY_LEVEL", "sal_min": 5.5, "sal_max": 8.0, "location": "Bengaluru"},
            {"title": "Automation Intern", "category": "Automation", "type": "INTERNSHIP", "level": "ENTRY_LEVEL", "sal_min": 3.0, "sal_max": 5.0, "location": "Nashik"},
        ],
        "skills": [
            ("PLC Programming", "INTERMEDIATE", 2.0),
            ("SCADA", "INTERMEDIATE", 1.5),
            ("Power Systems", "INTERMEDIATE", 2.0),
            ("MATLAB", "BEGINNER", 1.0),
        ],
        "rec_courses": ["PLC Programming & Industrial Automation", "Power Electronics & Converters"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Written Test", "order": 1, "desc": "Power systems, electrical machines, PLC fundamentals."},
            {"name": "Technical Interview", "order": 2, "desc": "Drives, automation, panel wiring."},
            {"name": "HR & Manager Round", "order": 3, "desc": "Career goals, relocation preference."},
        ],
        "interview_qs": [
            {"q": "What is a Variable Frequency Drive (VFD) and its purpose?", "diff": "EASY", "cat": "TECHNICAL", "ans": "VFD controls motor speed by varying frequency and voltage of power supply, saving energy."},
            {"q": "Explain the difference between synchronous and asynchronous motors.", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "Synchronous: runs at synchronous speed, rotor locked to field. Async: slip exists between rotor and field."},
        ],
        "branches": ["EEE"],
    },
    {
        "name": "Siemens India",
        "industry": "Power & Automation",
        "headquarters": "Mumbai, Maharashtra",
        "description": "Siemens India provides smart grid, power distribution, and automation solutions. Hires EEE graduates for SCADA, PLC, and energy management roles.",
        "company_size": "10,000+ employees",
        "website": "https://www.siemens.com/in/en.html",
        "careers_url": "https://jobs.siemens.com/jobs",
        "linkedin_url": "https://www.linkedin.com/company/siemens",
        "is_hiring": True,
        "job_roles": [
            {"title": "Power Systems Engineer Trainee", "category": "Electrical", "type": "TRAINEE", "level": "ENTRY_LEVEL", "sal_min": 6.0, "sal_max": 9.0, "location": "Mumbai"},
            {"title": "SCADA & Automation Intern", "category": "Automation", "type": "INTERNSHIP", "level": "ENTRY_LEVEL", "sal_min": 3.5, "sal_max": 5.5, "location": "Gurgaon"},
        ],
        "skills": [
            ("SCADA", "ADVANCED", 2.5),
            ("PLC Programming", "ADVANCED", 2.5),
            ("Power Systems", "INTERMEDIATE", 2.0),
        ],
        "rec_courses": ["PLC Programming & Industrial Automation"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Online Aptitude Test", "order": 1, "desc": "Quantitative + technical electrical questions."},
            {"name": "Technical Panel Interview", "order": 2, "desc": "SCADA, protection relays, energy management."},
        ],
        "interview_qs": [
            {"q": "What is SCADA and how does it differ from DCS?", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "SCADA: supervisory control for wide-area infrastructure. DCS: distributed control for process industries."},
            {"q": "Explain distance protection in power systems.", "diff": "HARD", "cat": "TECHNICAL", "ans": "Distance relay measures impedance to fault. Zones (1, 2, 3) with time delays for selectivity."},
        ],
        "branches": ["EEE"],
    },
    {
        "name": "Tata Power",
        "industry": "Energy",
        "headquarters": "Mumbai, Maharashtra",
        "description": "Tata Power is India's leading integrated power company covering generation, transmission, and distribution. Recruits EEE graduates for power plant, grid, and solar projects.",
        "company_size": "5,000-10,000 employees",
        "website": "https://www.tatapower.com",
        "careers_url": "https://www.tatapower.com/careers",
        "linkedin_url": "https://www.linkedin.com/company/tata-power",
        "is_hiring": True,
        "job_roles": [
            {"title": "Graduate Engineer Trainee - EEE", "category": "Electrical", "type": "TRAINEE", "level": "ENTRY_LEVEL", "sal_min": 5.0, "sal_max": 7.5, "location": "Pan-India"},
        ],
        "skills": [
            ("Power Systems", "ADVANCED", 3.0),
            ("MATLAB", "INTERMEDIATE", 1.5),
            ("PLC Programming", "BEGINNER", 1.0),
        ],
        "rec_courses": ["Power Electronics & Converters"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Group Discussion", "order": 1, "desc": "Topic: renewable energy, smart grids, sustainability."},
            {"name": "Technical Interview", "order": 2, "desc": "Power generation, switchgear, protective relaying."},
            {"name": "HR Interview", "order": 3, "desc": "STAR questions, location preference."},
        ],
        "interview_qs": [
            {"q": "What are the types of power generation plants?", "diff": "EASY", "cat": "TECHNICAL", "ans": "Thermal, hydro, nuclear, solar, wind, tidal."},
            {"q": "Explain the working of a circuit breaker.", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "Interrupts fault current by quenching the arc using oil, air, SF6, or vacuum mechanisms."},
        ],
        "branches": ["EEE"],
    },

    # ─── Mechanical-focused ───────────────────────────────────────────────────
    {
        "name": "Tata Motors",
        "industry": "Automotive",
        "headquarters": "Mumbai, Maharashtra",
        "description": "Tata Motors is India's largest automotive manufacturer. Hires mechanical engineers for vehicle design, manufacturing, NVH, and EV powertrain development.",
        "company_size": "10,000+ employees",
        "website": "https://www.tatamotors.com",
        "careers_url": "https://careers.tatamotors.com",
        "linkedin_url": "https://www.linkedin.com/company/tata-motors",
        "is_hiring": True,
        "job_roles": [
            {"title": "Graduate Engineer Trainee - Mechanical", "category": "Mechanical", "type": "TRAINEE", "level": "ENTRY_LEVEL", "sal_min": 5.5, "sal_max": 8.5, "location": "Pune"},
            {"title": "Design Engineering Intern", "category": "Mechanical", "type": "INTERNSHIP", "level": "ENTRY_LEVEL", "sal_min": 3.0, "sal_max": 5.0, "location": "Pune"},
        ],
        "skills": [
            ("SolidWorks", "INTERMEDIATE", 2.0),
            ("AutoCAD", "INTERMEDIATE", 1.5),
            ("Finite Element Analysis", "INTERMEDIATE", 2.0),
            ("Thermodynamics", "INTERMEDIATE", 1.5),
        ],
        "rec_courses": ["3D Modelling with SolidWorks", "Finite Element Analysis with ANSYS"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Online Aptitude Test", "order": 1, "desc": "Quantitative aptitude + technical engineering questions."},
            {"name": "Technical Interview", "order": 2, "desc": "CAD, manufacturing processes, GD&T."},
            {"name": "HR Interview", "order": 3, "desc": "Goals, relocation, team dynamics."},
        ],
        "interview_qs": [
            {"q": "What is GD&T and why is it used in engineering drawings?", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "Geometric Dimensioning & Tolerancing: standardized system for defining permissible variations in form, orientation, and location."},
            {"q": "Explain the concept of stress concentration.", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "Localized increase in stress around geometric discontinuities (notches, holes). Described by stress concentration factor Kt."},
        ],
        "branches": ["Mechanical"],
    },
    {
        "name": "Mahindra & Mahindra",
        "industry": "Automotive",
        "headquarters": "Mumbai, Maharashtra",
        "description": "Mahindra designs SUVs, tractors, and electric vehicles. Recruits mechanical engineers for product development, R&D, and manufacturing engineering.",
        "company_size": "10,000+ employees",
        "website": "https://www.mahindra.com",
        "careers_url": "https://careers.mahindra.com",
        "linkedin_url": "https://www.linkedin.com/company/mahindrarise",
        "is_hiring": True,
        "job_roles": [
            {"title": "Manufacturing Engineer Trainee", "category": "Mechanical", "type": "TRAINEE", "level": "ENTRY_LEVEL", "sal_min": 5.0, "sal_max": 7.0, "location": "Nashik"},
            {"title": "R&D Mechanical Intern", "category": "Mechanical", "type": "INTERNSHIP", "level": "ENTRY_LEVEL", "sal_min": 3.0, "sal_max": 4.5, "location": "Chakan"},
        ],
        "skills": [
            ("SolidWorks", "INTERMEDIATE", 2.0),
            ("CNC Machining", "INTERMEDIATE", 1.5),
            ("Finite Element Analysis", "BEGINNER", 1.0),
        ],
        "rec_courses": ["3D Modelling with SolidWorks"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Technical MCQ Test", "order": 1, "desc": "Mechanical engineering fundamentals, manufacturing."},
            {"name": "Technical Interview", "order": 2, "desc": "CAD tools, tolerance analysis, BOM."},
        ],
        "interview_qs": [
            {"q": "What is the difference between casting and forging?", "diff": "EASY", "cat": "TECHNICAL", "ans": "Casting: liquid metal poured into mold. Forging: solid metal deformed by compression for higher strength."},
            {"q": "Explain the working of a hydraulic press.", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "Pascal's law: pressure applied to enclosed fluid transmits equally. Small force on small piston → large force on large piston."},
        ],
        "branches": ["Mechanical"],
    },
    {
        "name": "ISRO (VSSC)",
        "industry": "Aerospace & Defense",
        "headquarters": "Thiruvananthapuram, Kerala",
        "description": "ISRO's Vikram Sarabhai Space Centre (VSSC) develops rockets and spacecraft. Recruits mechanical engineers for propulsion, structural design, and thermal analysis.",
        "company_size": "5,000-10,000 employees",
        "website": "https://www.isro.gov.in",
        "careers_url": "https://www.isro.gov.in/recruitment-list",
        "linkedin_url": "https://www.linkedin.com/company/isro",
        "is_hiring": True,
        "job_roles": [
            {"title": "Scientist/Engineer SC - Mechanical", "category": "Aerospace", "type": "FULL_TIME", "level": "ENTRY_LEVEL", "sal_min": 7.0, "sal_max": 10.0, "location": "Thiruvananthapuram"},
        ],
        "skills": [
            ("Finite Element Analysis", "ADVANCED", 3.0),
            ("SolidWorks", "ADVANCED", 2.0),
            ("Thermodynamics", "ADVANCED", 2.5),
            ("MATLAB", "INTERMEDIATE", 1.5),
        ],
        "rec_courses": ["Finite Element Analysis with ANSYS", "3D Modelling with SolidWorks"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "ISRO Centralized Recruitment Test", "order": 1, "desc": "National level exam: mechanical engineering fundamentals, aptitude."},
            {"name": "Technical Interview", "order": 2, "desc": "Rocket propulsion, structural analysis, thermal systems."},
        ],
        "interview_qs": [
            {"q": "What is the specific impulse of a rocket engine?", "diff": "HARD", "cat": "TECHNICAL", "ans": "Specific impulse (Isp) = thrust / weight flow rate of propellant. Measures propulsion efficiency."},
            {"q": "Explain buckling in structural members.", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "Sudden lateral deflection of slender member under compressive load. Euler's formula: Pcr = π²EI / (KL)²."},
        ],
        "branches": ["Mechanical"],
    },

    # ─── Cross-branch (hires from multiple branches) ──────────────────────────
    {
        "name": "Bosch India",
        "industry": "Automotive Technology",
        "headquarters": "Bengaluru, Karnataka",
        "description": "Bosch India develops automotive electronics, ADAS, connected mobility, and IoT solutions. Hires across ECE, EEE, and Mechanical branches for diverse technical roles.",
        "company_size": "10,000+ employees",
        "website": "https://www.bosch.in",
        "careers_url": "https://www.bosch.in/careers/",
        "linkedin_url": "https://www.linkedin.com/company/bosch",
        "is_hiring": True,
        "job_roles": [
            {"title": "Embedded Software Engineer", "category": "Embedded", "type": "FULL_TIME", "level": "ENTRY_LEVEL", "sal_min": 8.0, "sal_max": 13.0, "location": "Bengaluru"},
            {"title": "Automotive Design Intern", "category": "Mechanical", "type": "INTERNSHIP", "level": "ENTRY_LEVEL", "sal_min": 4.0, "sal_max": 6.0, "location": "Bengaluru"},
        ],
        "skills": [
            ("Embedded C", "INTERMEDIATE", 2.0),
            ("C Programming", "ADVANCED", 2.0),
            ("MATLAB", "INTERMEDIATE", 1.5),
            ("SolidWorks", "BEGINNER", 1.0),
            ("Python", "BEGINNER", 1.0),
        ],
        "rec_courses": ["C Programming for Engineers", "Embedded Systems with Arduino"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Online Test", "order": 1, "desc": "Technical MCQs + C coding."},
            {"name": "Technical Interview - Automotive", "order": 2, "desc": "CAN bus, AUTOSAR, sensor fusion."},
            {"name": "HR Interview", "order": 3, "desc": "Behavioral questions, Bosch competency model."},
        ],
        "interview_qs": [
            {"q": "What is the CAN bus protocol and why is it used in automobiles?", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "Controller Area Network: robust serial communication for ECUs. Multi-master, differential signaling, error detection."},
            {"q": "Explain AUTOSAR architecture.", "diff": "HARD", "cat": "TECHNICAL", "ans": "Layered automotive software standard: Application Layer → RTE → BSW (Services, ECU Abstraction, MCAL) → Hardware."},
        ],
        "branches": ["ECE", "Mechanical"],
    },
    {
        "name": "Infosys BPM",
        "industry": "IT & Consulting",
        "headquarters": "Bengaluru, Karnataka",
        "description": "Infosys BPM provides business process outsourcing and digital transformation services. Hires from all engineering branches for technology consulting, automation, and AI-powered analytics.",
        "company_size": "10,000+ employees",
        "website": "https://www.infosysbpm.com",
        "careers_url": "https://www.infosys.com/careers/",
        "linkedin_url": "https://www.linkedin.com/company/infosys",
        "is_hiring": True,
        "job_roles": [
            {"title": "Systems Engineer", "category": "Software", "type": "FULL_TIME", "level": "ENTRY_LEVEL", "sal_min": 3.6, "sal_max": 6.0, "location": "Pan-India"},
            {"title": "Automation Analyst Intern", "category": "Automation", "type": "INTERNSHIP", "level": "ENTRY_LEVEL", "sal_min": 2.5, "sal_max": 4.0, "location": "Pan-India"},
        ],
        "skills": [
            ("Python", "BEGINNER", 1.5),
            ("Data Structures", "INTERMEDIATE", 2.0),
            ("Machine Learning", "BEGINNER", 1.0),
        ],
        "rec_courses": ["Python for AI & Data Science"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "Online Aptitude + Pseudocode Test", "order": 1, "desc": "Logical reasoning, verbal, basic coding."},
            {"name": "Technical Interview", "order": 2, "desc": "Programming fundamentals, OOPS, basic ML."},
            {"name": "HR Interview", "order": 3, "desc": "STAR, flexibility, training willingness."},
        ],
        "interview_qs": [
            {"q": "What is the difference between OOP and Procedural programming?", "diff": "EASY", "cat": "TECHNICAL", "ans": "OOP: encapsulation, inheritance, polymorphism. Procedural: sequential functions, no encapsulation."},
            {"q": "Explain REST API and its HTTP methods.", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "GET (read), POST (create), PUT (update), DELETE (delete). Stateless client-server architecture."},
        ],
        "branches": ["AIML", "ECE", "EEE", "Mechanical"],
    },
    {
        "name": "Wipro Technologies",
        "industry": "IT & Consulting",
        "headquarters": "Bengaluru, Karnataka",
        "description": "Wipro is a global IT and engineering services company. Recruits from all engineering branches through campus programs with focus on digital transformation, AI, and embedded systems.",
        "company_size": "10,000+ employees",
        "website": "https://www.wipro.com",
        "careers_url": "https://careers.wipro.com",
        "linkedin_url": "https://www.linkedin.com/company/wipro",
        "is_hiring": True,
        "job_roles": [
            {"title": "Project Engineer", "category": "Software", "type": "FULL_TIME", "level": "ENTRY_LEVEL", "sal_min": 3.5, "sal_max": 5.5, "location": "Pan-India"},
            {"title": "Intern Engineer", "category": "Software", "type": "INTERNSHIP", "level": "ENTRY_LEVEL", "sal_min": 2.5, "sal_max": 3.5, "location": "Pan-India"},
        ],
        "skills": [
            ("Python", "BEGINNER", 1.5),
            ("Data Structures", "INTERMEDIATE", 2.0),
            ("C Programming", "BEGINNER", 1.0),
        ],
        "rec_courses": ["Python for AI & Data Science", "C Programming for Engineers"],
        "rec_projects": [],
        "rec_certs": [],
        "interview_rounds": [
            {"name": "NLTH Online Test", "order": 1, "desc": "Wipro National Level Talent Hunt: aptitude, coding, English."},
            {"name": "Technical Interview", "order": 2, "desc": "Basic CS fundamentals, programming, data structures."},
            {"name": "HR Interview", "order": 3, "desc": "STAR methodology, flexibility, long-term goals."},
        ],
        "interview_qs": [
            {"q": "What is the time complexity of binary search?", "diff": "EASY", "cat": "TECHNICAL", "ans": "O(log n) — divides the search space in half each iteration."},
            {"q": "Explain TCP vs UDP.", "diff": "MEDIUM", "cat": "TECHNICAL", "ans": "TCP: connection-oriented, reliable, ordered. UDP: connectionless, fast, no guarantees (streaming, gaming)."},
        ],
        "branches": ["AIML", "ECE", "EEE", "Mechanical"],
    },
]
